### ISSUE TITLE
Bower version conflicts

### ISSUE THREAD

**Issue by nsaunders** [purescript-hyper/purescript-hypertrout#13]
Presumably due to upstream dependency changes, installing ```purescript-hypertrout``` in a clean directory via Bower results in version conflict resolution prompts. This is a recurring problem, even in spite of the [```resolutions```](https://github.com/owickstrom/purescript-hypertrout/blob/master/bower.json#L26) added by @owickstrom. The solution is probably to add ```purescript-hypertrout``` and related projects to [package-sets](https://github.com/purescript/package-sets) as suggested in [owickstrom/hyper#54](https://github.com/owickstrom/hyper/issues/54). Probably managing dependencies primarily with [spago](https://github.com/spacchetti/spago) or [psc-package](https://github.com/purescript/psc-package) would be helpful as well.

**Comment by owickstrom** [comment]
I don't have much to add here, not really up-to-date with the packaging/deps situation in PureScript nowadays. Do you mean dropping Bower support and using one or both of the others?

**Comment by nsaunders** [comment]
In the case of my [dotenv](https://github.com/nicholassaunders/purescript-dotenv) library, I have switched to [spago](https://github.com/spacchetti/spago). What this means, although I continue to maintain the [bower.json](https://github.com/nicholassaunders/purescript-dotenv/blob/master/bower.json) file, is that [spago.dhall](https://github.com/nicholassaunders/purescript-dotenv/blob/master/spago.dhall) has become the canonical source for the list of dependencies, while the package set provides the version number for each dependency. I am looking forward to being able to use spago to [generate a bower.json file](https://github.com/spacchetti/spago/issues/204) in the future, but for now ```spago list-packages -f direct``` generates the list of dependencies that need to be (manually) included in bower.json. Finally, [Travis is configured](https://github.com/nicholassaunders/purescript-dotenv/blob/master/.travis.yml) to install dependencies and build the project using both spago and bower/pulp.

I think this is a pretty solid solution for users of spago or psc-package. It is not a perfect solution for Bower users; but at least maintaining bower.json with consistent version numbers should be immediately easier. In the future, perhaps I might find a CI solution that responds to new package sets being published, attempting to build with the new package set and automatically re-generating bower.json upon success.

Anyway, I thought maybe I would try the same setup over here if it seems to work out OK. If you have any thoughts or questions after reading this, please let me know!

**Comment by nsaunders** [comment]
I have implemented the same thing in [purescript-trout#12](https://github.com/owickstrom/purescript-trout/pull/12) in the process of the 0.13 updates.

**Comment by owickstrom** [comment]
@nicholassaunders I like the plan! Also, when it comes to the Hyper/Trout packages, they're marked experimental (at least Hyper is) and not really used in production by anyone AFAIK. Requiring Spago for now is fine, I think, but if we can get Bower compat that's nice.

**Comment by nsaunders** [comment]
Fortunately, clients will still be able to use Bower, and Spago is just there for dev/CI. When we add Hypertrout to package-sets, clients will be able to choose psc-package or Spago, or they can stick with Bower the if they really want to. :-)
