### ISSUE TITLE
Use Hyper.Form.Urlencoded

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [purescript-hyper/purescript-hypertrout#5]
For query strings. Also use `parseUrl` for the path.

Depends on https://github.com/owickstrom/hyper/pull/35.
Depends on https://github.com/owickstrom/purescript-trout/pull/4.

**Comment by owickstrom** [comment]
This can be closed, right?

**Comment by no-longer-on-githu-b** [comment]
Yes

Sent from my iPhone.
